### PR TITLE
build(gem): support Rails 6.0

### LINKED ISSUE #3: Support Rails 6.0
# Problem

I couldn't update Rails to 6 for projects containing this library

- [ ] repro.

```
Bundler could not find compatible versions for gem "activejob":
  In Gemfile:
    active_job-disable was resolved to 0.2.1, which depends on
      activejob (>= 5.0, < 6)

    rails (= 6.0.4.3) was resolved to 6.0.4.3, which depends on
      activejob (= 6.0.4.3)
```

# Possible solution

change deps

https://github.com/smartoperation/active_job-disable/blob/dae333aaf41a37e9e3a10c427c8d02c0435ba395/active_job-disable.gemspec#L24

# Consideration

- [ ] ...

### PR DESCRIPTION
**Pull request by k-sonoda-biztex**
Relates to #3

# How has this been tested?

```sh
export BUNDLE_GEMFILE=gemfiles/rails_6.0.gemfile
bundle && bundle exec rake
```

Out of scope:

- CircleCI [Matrix jobs](https://circleci.com/blog/circleci-matrix-jobs/)
- Testing Rails 6.2

### CODE REVIEW

**Comment by k-sonoda-biztex** [comment]
Could you take a look at this? @huynhit-biztex-92

**Review by huynhit-biztex-92 — APPROVED** [review]
LGTM

**Comment by k-sonoda-biztex** [comment]
:memo: The checkout was failing. I added Deploy keys and solved the problem.
I followed the menu "Checkout SSH Keys" in the Project Settings on the CircleCI side. Then it seems to have been automatically added to the GitHub side.

**Comment by k-sonoda-biztex** [comment]
:memo: The checkout was failing. I added Deploy keys and solved the problem.
I followed the menu "Checkout SSH Keys" in the Project Settings on the CircleCI side. Then it seems to have been automatically added to the GitHub side.

**Pull request merged**
